spring.application.name=backend-api
server.port=8081
# 1. Thông tin kết nối Database H2 (chạy trên RAM)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Cấu hình JPA / Hibernate
# Dòng này cực kỳ quan trọng: Nó bảo Spring Boot hãy tự động tạo bảng (CREATE TABLE) dựa trên class @Entity của bạn
spring.jpa.hibernate.ddl-auto=update
# Dòng này giúp in ra các câu lệnh SQL ở Terminal để Tech Lead dễ debug
spring.jpa.show-sql=true