name: Spring Boot CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql-db:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: root123
          MYSQL_DATABASE: backend_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - name: Tải code từ kho chứa
      uses: actions/checkout@v3

    - name: Cài đặt Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven 

    - name: Cấp quyền thực thi
      run: chmod +x mvnw

    - name: Build và Test
      run: ./mvnw clean package
